# Generated by Django 5.2 on 2025-07-14 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='productcart',
            name='price',
            field=models.CharField(),
        ),
    ]
