# Generated by Django 5.2 on 2025-07-14 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0010_alter_order_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcart',
            name='order_id',
            field=models.IntegerField(auto_created=True),
        ),
        migrations.AlterField(
            model_name='productcart',
            name='order_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('ordered', 'Ordered')], default='pending'),
        ),
    ]
