# Generated by Django 5.2 on 2025-07-14 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0012_alter_productcart_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending'),
        ),
    ]
