# Generated by Django 5.2 on 2025-07-14 20:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0013_alter_payment_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='rating',
            field=models.FloatField(validators=[django.core.validators.MaxValueValidator(5)]),
        ),
    ]
