# Generated by Django 5.2 on 2025-07-14 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0015_alter_contact_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='image',
            new_name='img',
        ),
    ]
