# Generated by Django 5.2 on 2025-07-14 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0016_rename_image_userprofile_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='image',
            new_name='img',
        ),
    ]
